# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fhd/final.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 780)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.InputBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputBox.sizePolicy().hasHeightForWidth())
        self.InputBox.setSizePolicy(sizePolicy)
        self.InputBox.setObjectName("InputBox")
        self.formLayout = QtWidgets.QFormLayout(self.InputBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.InputBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.stab1u = QtWidgets.QSpinBox(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stab1u.sizePolicy().hasHeightForWidth())
        self.stab1u.setSizePolicy(sizePolicy)
        self.stab1u.setMinimum(1)
        self.stab1u.setMaximum(6)
        self.stab1u.setObjectName("stab1u")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stab1u)
        self.label_3 = QtWidgets.QLabel(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.qu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qu.sizePolicy().hasHeightForWidth())
        self.qu.setSizePolicy(sizePolicy)
        self.qu.setObjectName("qu")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.qu)
        self.label_4 = QtWidgets.QLabel(self.InputBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.hu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hu.sizePolicy().hasHeightForWidth())
        self.hu.setSizePolicy(sizePolicy)
        self.hu.setObjectName("hu")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hu)
        self.label_5 = QtWidgets.QLabel(self.InputBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.dayu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dayu.sizePolicy().hasHeightForWidth())
        self.dayu.setSizePolicy(sizePolicy)
        self.dayu.setObjectName("dayu")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dayu)
        self.label_6 = QtWidgets.QLabel(self.InputBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.outputu = QtWidgets.QComboBox(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputu.sizePolicy().hasHeightForWidth())
        self.outputu.setSizePolicy(sizePolicy)
        self.outputu.setObjectName("outputu")
        self.outputu.addItem("")
        self.outputu.addItem("")
        self.outputu.addItem("")
        self.outputu.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.outputu)
        self.label_7 = QtWidgets.QLabel(self.InputBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.windu = QtWidgets.QComboBox(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windu.sizePolicy().hasHeightForWidth())
        self.windu.setSizePolicy(sizePolicy)
        self.windu.setObjectName("windu")
        self.windu.addItem("")
        self.windu.addItem("")
        self.windu.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.windu)
        self.label_8 = QtWidgets.QLabel(self.InputBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.humidifyu = QtWidgets.QComboBox(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidifyu.sizePolicy().hasHeightForWidth())
        self.humidifyu.setSizePolicy(sizePolicy)
        self.humidifyu.setObjectName("humidifyu")
        self.humidifyu.addItem("")
        self.humidifyu.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.humidifyu)
        self.horizontalLayout.addWidget(self.InputBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image = QtWidgets.QLabel(self.groupBox_2)
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.verticalLayout_2.addWidget(self.image)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button.sizePolicy().hasHeightForWidth())
        self.button.setSizePolicy(sizePolicy)
        self.button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button.setCheckable(False)
        self.button.setObjectName("button")
        self.verticalLayout.addWidget(self.button, 0, QtCore.Qt.AlignHCenter)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button.clicked.connect(self.click_actions)
        #self.button.clicked.connect(self.update_inputs)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InputBox.setTitle(_translate("MainWindow", "Input"))
        self.label.setText(_translate("MainWindow", "stability (1-6)"))
        self.stab1u.setToolTip(_translate("MainWindow", "<html><head/><body><p>set from 1-6</p><p>1- very unstable</p><p>6-very stable</p></body></html>"))
        self.stab1u.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>help</p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Q (g/s)"))
        self.qu.setToolTip(_translate("MainWindow", "<html><head/><body><p>mass emmited per unit time</p></body></html>"))
        self.qu.setText(_translate("MainWindow", "40"))
        self.label_4.setText(_translate("MainWindow", "Height of Stack (m)"))
        self.hu.setToolTip(_translate("MainWindow", "<html><head/><body><p>Height of stack in meter</p></body></html>"))
        self.hu.setText(_translate("MainWindow", "50"))
        self.label_5.setText(_translate("MainWindow", "days"))
        self.dayu.setToolTip(_translate("MainWindow", "<html><head/><body><p>run model for 365 days</p></body></html>"))
        self.dayu.setText(_translate("MainWindow", "50"))
        self.label_6.setText(_translate("MainWindow", "Output Type"))
        self.outputu.setItemText(0, _translate("MainWindow", "Plan View"))
        self.outputu.setItemText(1, _translate("MainWindow", "Height Slice"))
        self.outputu.setItemText(2, _translate("MainWindow", "Surface Time"))
        self.outputu.setItemText(3, _translate("MainWindow", "No Plot"))
        self.label_7.setText(_translate("MainWindow", "Wind Type"))
        self.windu.setItemText(0, _translate("MainWindow", "Constanst Wind"))
        self.windu.setItemText(1, _translate("MainWindow", "Fluctuating Wind"))
        self.windu.setItemText(2, _translate("MainWindow", "Previaling Wind"))
        self.label_8.setText(_translate("MainWindow", "Humidify?"))
        self.humidifyu.setItemText(0, _translate("MainWindow", "Dry Aerosol"))
        self.humidifyu.setItemText(1, _translate("MainWindow", "Humidify"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output"))
        self.button.setText(_translate("MainWindow", "calculate!"))

    def click_actions(self):
        from model_gauss import gauss_model
        from PyQt5.QtGui import QImage
        
        model = gauss_model()
        self.update_inputs(model)
        model.run(self.progressBar)

        size = model.canvas.size()
        width, height = size.width(), size.height()
        im = QImage(model.canvas.buffer_rgba(), width, height, QImage.Format_ARGB32)
        self.image.setPixmap(QtGui.QPixmap(im))
        self.image.show()
    
    def update_inputs(self,model):
        model.stab1 = self.stab1u.value()
        model.Q[0] = int(self.qu.text())
        model.H[0] = int(self.hu.text())
        model.days = int(self.dayu.text())
        model.output = self.outputu.currentIndex() + 1
        model.wind = self.windu.currentIndex() + 1
        model.humidify = self.humidifyu.currentIndex() + 1


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
