# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fhd/final.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 963)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.InputBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputBox.sizePolicy().hasHeightForWidth())
        self.InputBox.setSizePolicy(sizePolicy)
        self.InputBox.setObjectName("InputBox")
        self.formLayout = QtWidgets.QFormLayout(self.InputBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.InputBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.stab1u = QtWidgets.QSpinBox(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stab1u.sizePolicy().hasHeightForWidth())
        self.stab1u.setSizePolicy(sizePolicy)
        self.stab1u.setMinimum(1)
        self.stab1u.setMaximum(6)
        self.stab1u.setObjectName("stab1u")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stab1u)
        self.label_15 = QtWidgets.QLabel(self.InputBox)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Urban = QtWidgets.QRadioButton(self.InputBox)
        self.Urban.setChecked(False)
        self.Urban.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.Urban)
        self.Rural = QtWidgets.QRadioButton(self.InputBox)
        self.Rural.setChecked(True)
        self.Rural.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.Rural)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_14 = QtWidgets.QLabel(self.InputBox)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.windspeedu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windspeedu.sizePolicy().hasHeightForWidth())
        self.windspeedu.setSizePolicy(sizePolicy)
        self.windspeedu.setObjectName("windspeedu")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.windspeedu)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_3 = QtWidgets.QLabel(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.qu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qu.sizePolicy().hasHeightForWidth())
        self.qu.setSizePolicy(sizePolicy)
        self.qu.setObjectName("qu")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.qu)
        self.label_4 = QtWidgets.QLabel(self.InputBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.hu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hu.sizePolicy().hasHeightForWidth())
        self.hu.setSizePolicy(sizePolicy)
        self.hu.setObjectName("hu")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.hu)
        self.label_5 = QtWidgets.QLabel(self.InputBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.dayu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dayu.sizePolicy().hasHeightForWidth())
        self.dayu.setSizePolicy(sizePolicy)
        self.dayu.setObjectName("dayu")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.dayu)
        self.label_11 = QtWidgets.QLabel(self.InputBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(25, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.xu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xu.sizePolicy().hasHeightForWidth())
        self.xu.setSizePolicy(sizePolicy)
        self.xu.setObjectName("xu")
        self.formLayout.setWidget(25, QtWidgets.QFormLayout.FieldRole, self.xu)
        self.label_12 = QtWidgets.QLabel(self.InputBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(26, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.yu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yu.sizePolicy().hasHeightForWidth())
        self.yu.setSizePolicy(sizePolicy)
        self.yu.setObjectName("yu")
        self.formLayout.setWidget(26, QtWidgets.QFormLayout.FieldRole, self.yu)
        self.label_13 = QtWidgets.QLabel(self.InputBox)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(27, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.zu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zu.sizePolicy().hasHeightForWidth())
        self.zu.setSizePolicy(sizePolicy)
        self.zu.setObjectName("zu")
        self.formLayout.setWidget(27, QtWidgets.QFormLayout.FieldRole, self.zu)
        self.label_6 = QtWidgets.QLabel(self.InputBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(29, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.outputu = QtWidgets.QComboBox(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputu.sizePolicy().hasHeightForWidth())
        self.outputu.setSizePolicy(sizePolicy)
        self.outputu.setObjectName("outputu")
        self.outputu.addItem("")
        self.outputu.addItem("")
        self.outputu.addItem("")
        self.outputu.addItem("")
        self.formLayout.setWidget(29, QtWidgets.QFormLayout.FieldRole, self.outputu)
        self.label_10 = QtWidgets.QLabel(self.InputBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(30, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.domainu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domainu.sizePolicy().hasHeightForWidth())
        self.domainu.setSizePolicy(sizePolicy)
        self.domainu.setObjectName("domainu")
        self.formLayout.setWidget(30, QtWidgets.QFormLayout.FieldRole, self.domainu)
        self.label_2 = QtWidgets.QLabel(self.InputBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(31, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dxyu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dxyu.sizePolicy().hasHeightForWidth())
        self.dxyu.setSizePolicy(sizePolicy)
        self.dxyu.setObjectName("dxyu")
        self.formLayout.setWidget(31, QtWidgets.QFormLayout.FieldRole, self.dxyu)
        self.label_9 = QtWidgets.QLabel(self.InputBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(32, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.dzu = QtWidgets.QLineEdit(self.InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dzu.sizePolicy().hasHeightForWidth())
        self.dzu.setSizePolicy(sizePolicy)
        self.dzu.setObjectName("dzu")
        self.formLayout.setWidget(32, QtWidgets.QFormLayout.FieldRole, self.dzu)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(18, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(20, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(28, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.horizontalLayout.addWidget(self.InputBox)
        self.OutputBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputBox.sizePolicy().hasHeightForWidth())
        self.OutputBox.setSizePolicy(sizePolicy)
        self.OutputBox.setObjectName("OutputBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OutputBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.image = QtWidgets.QLabel(self.OutputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.verticalLayout_6.addWidget(self.image)
        self.groupBox = QtWidgets.QGroupBox(self.OutputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.pullu = QtWidgets.QLabel(self.groupBox)
        self.pullu.setText("")
        self.pullu.setObjectName("pullu")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pullu)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.maxu = QtWidgets.QLabel(self.groupBox)
        self.maxu.setText("")
        self.maxu.setObjectName("maxu")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.maxu)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addWidget(self.OutputBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button.sizePolicy().hasHeightForWidth())
        self.button.setSizePolicy(sizePolicy)
        self.button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button.setCheckable(False)
        self.button.setObjectName("button")
        self.verticalLayout.addWidget(self.button, 0, QtCore.Qt.AlignHCenter)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.button.clicked.connect(self.click_actions)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InputBox.setTitle(_translate("MainWindow", "Input"))
        self.label.setText(_translate("MainWindow", "stability (1-6)"))
        self.stab1u.setToolTip(_translate("MainWindow", "<html><head/><body><p>set from 1-6</p><p>1- very unstable</p><p>6-very stable</p></body></html>"))
        self.stab1u.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>help</p><p><br/></p></body></html>"))
        self.label_15.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is necessary for calculating sigma</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Status"))
        self.Urban.setText(_translate("MainWindow", "Urban"))
        self.Rural.setText(_translate("MainWindow", "Rural"))
        self.label_14.setToolTip(_translate("MainWindow", "<html><head/><body><p>wind speed at stack height (m/s)</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "Wind Speed"))
        self.windspeedu.setToolTip(_translate("MainWindow", "<html><head/><body><p>wind speed at stack height (m/s)</p></body></html>"))
        self.windspeedu.setText(_translate("MainWindow", "5"))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>mass emmited per unit time</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Q (g/s)"))
        self.qu.setToolTip(_translate("MainWindow", "<html><head/><body><p>mass emmited per unit time</p></body></html>"))
        self.qu.setText(_translate("MainWindow", "40"))
        self.label_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Height of stack in meter</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Height of Stack"))
        self.hu.setToolTip(_translate("MainWindow", "<html><head/><body><p>Height of stack in meter</p></body></html>"))
        self.hu.setText(_translate("MainWindow", "50"))
        self.label_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>run model for &lt;365&gt; days</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "days"))
        self.dayu.setToolTip(_translate("MainWindow", "<html><head/><body><p>run model for &lt;365&gt; days</p></body></html>"))
        self.dayu.setText(_translate("MainWindow", "50"))
        self.label_11.setToolTip(_translate("MainWindow", "<html><head/><body><p>enter the cordinates you want to get the results at</p><p>x,y for PlanView</p><p>y,z for HeightSlice</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Reciver Point X"))
        self.xu.setToolTip(_translate("MainWindow", "<html><head/><body><p>enter the cordinates you want to get the results at</p><p>x,y for PlanView</p><p>y,z for HeightView</p></body></html>"))
        self.xu.setText(_translate("MainWindow", "10"))
        self.label_12.setToolTip(_translate("MainWindow", "<html><head/><body><p>enter the cordinates you want to get the results at</p><p>x,y for PlanView</p><p>y,z for HeightView</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Reciver Point Y"))
        self.yu.setToolTip(_translate("MainWindow", "<html><head/><body><p>enter the cordinates you want to get the results at</p><p>x,y for PlanView</p><p>y,z for HeightView</p></body></html>"))
        self.yu.setText(_translate("MainWindow", "500"))
        self.label_13.setToolTip(_translate("MainWindow", "<html><head/><body><p>enter the cordinates you want to get the results at</p><p>x,y for PlanView</p><p>y,z for HeightView</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Reciver Point Z"))
        self.zu.setToolTip(_translate("MainWindow", "<html><head/><body><p>enter the cordinates you want to get the results at</p><p>x,y for PlanView</p><p>y,z for HeightView</p></body></html>"))
        self.zu.setText(_translate("MainWindow", "10"))
        self.label_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>what kind of plot do you want?</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Output Type"))
        self.outputu.setItemText(0, _translate("MainWindow", "Plan View"))
        self.outputu.setItemText(1, _translate("MainWindow", "Height Slice"))
        self.outputu.setItemText(2, _translate("MainWindow", "Surface Time"))
        self.outputu.setItemText(3, _translate("MainWindow", "No Plot"))
        self.label_10.setToolTip(_translate("MainWindow", "<html><head/><body><p>calculate out put for &lt;5&gt; km in &lt;5&gt;km domain</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "output domain (km)"))
        self.domainu.setToolTip(_translate("MainWindow", "<html><head/><body><p>solve for a &lt;?&gt; km domain, both x and y</p></body></html>"))
        self.domainu.setText(_translate("MainWindow", "5"))
        self.label_2.setText(_translate("MainWindow", "dxy"))
        self.dxyu.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Resolution of output in both x and y direction</p></body></html>"))
        self.dxyu.setText(_translate("MainWindow", "100"))
        self.label_9.setText(_translate("MainWindow", "dz"))
        self.dzu.setToolTip(_translate("MainWindow", "<html><head/><body><p>resolution of output in z direction</p></body></html>"))
        self.dzu.setText(_translate("MainWindow", "10"))
        self.OutputBox.setTitle(_translate("MainWindow", "Output"))
        self.groupBox.setTitle(_translate("MainWindow", "numerical outputs"))
        self.label_7.setText(_translate("MainWindow", "Pollution at Requested Point:"))
        self.label_8.setText(_translate("MainWindow", "Point of Maximum Pollution:"))
        self.button.setText(_translate("MainWindow", "calculate!"))


    def click_actions(self):
        _translate = QtCore.QCoreApplication.translate
        print('start')
        from model_gauss import gauss_model
        from PyQt5.QtGui import QImage
        model = gauss_model()
        self.update_inputs(model)
        model.run(self.progressBar)
        size = model.canvas.size()
        width, height = size.width(), size.height()
        im = QImage(model.canvas.buffer_rgba(), width, height, QImage.Format_ARGB32)
        self.image.setPixmap(QtGui.QPixmap(im))
        self.image.show()

        self.pullu.setText(_translate("MainWindow", str(model.pointpolution/1e6)))
        print(model.maxpoint)


    def update_inputs(self,model):
        model.stab1 = self.stab1u.value()
        model.Q[0] = int(self.qu.text())
        model.H[0] = int(self.hu.text())
        model.days = int(self.dayu.text())
        model.output = self.outputu.currentIndex() + 1
        model.wind_speed_int = int(self.windspeedu.text())
        model.reciver_x = int(self.xu.text())
        model.reciver_y = int(self.yu.text())
        model.reciver_z = int(self.zu.text())
        model.dxy = int(self.dxyu.text())
        model.dz = int(self.dzu.text())
        model.domain = int(self.domainu.text())
        model.Rural = self.Rural.isChecked()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
